<?php

declare(strict_types=1);

const DEFAULT_WILAYAH_ROOT = __DIR__.'/../../../laravel-wilayah';
const DEFAULT_SQL_PATH = __DIR__.'/../../src/Database/Sql/indonesia_regions.sql';
const DEFAULT_MANIFEST_PATH = __DIR__.'/../../data/version.php';

$wilayahRoot = $argv[1] ?? DEFAULT_WILAYAH_ROOT;
$targetSqlPath = $argv[2] ?? DEFAULT_SQL_PATH;
$manifestPath = $argv[3] ?? DEFAULT_MANIFEST_PATH;

$existingRows = parseExistingSql($targetSqlPath);
$mergedRows = collectRowsFromWilayah($wilayahRoot, $existingRows);

writeSqlFile($targetSqlPath, $mergedRows);
writeManifest($manifestPath, count($mergedRows), getenv('UPSTREAM_HASH') ?: 'unknown');

echo "Generated ".count($mergedRows)." rows into {$targetSqlPath}\n";

function collectRowsFromWilayah(string $wilayahRoot, array $existingRows): array
{
    $rows = [];

    foreach (loadPhpData($wilayahRoot.'/data/provinces.php') as $row) {
        $rows[] = mergeRow($row, $existingRows);
    }

    foreach (loadPhpData($wilayahRoot.'/data/regencies.php') as $row) {
        $rows[] = mergeRow($row, $existingRows);
    }

    foreach (glob($wilayahRoot.'/data/districts/*.php') ?: [] as $path) {
        foreach (loadPhpData($path) as $row) {
            $rows[] = mergeRow($row, $existingRows);
        }
    }

    foreach (glob($wilayahRoot.'/data/villages/*.php') ?: [] as $path) {
        foreach (loadPhpData($path) as $row) {
            $rows[] = mergeRow($row, $existingRows);
        }
    }

    usort($rows, static fn (array $a, array $b): int => strcmp($a['code'], $b['code']));

    return $rows;
}

function mergeRow(array $row, array $existingRows): array
{
    $code = (string) ($row['code'] ?? '');

    return [
        'code' => $code,
        'name' => (string) ($row['name'] ?? ''),
        'postal_code' => $row['postal_code'] ?? null,
    ];
}

function loadPhpData(string $path): array
{
    if (! file_exists($path)) {
        throw new RuntimeException("Wilayah data file not found: {$path}");
    }

    $data = require $path;

    return is_array($data) ? $data : [];
}

function parseExistingSql(string $path): array
{
    return [];
}

function writeSqlFile(string $path, array $rows): void
{
    $directory = dirname($path);
    if (! is_dir($directory) && ! mkdir($directory, 0755, true) && ! is_dir($directory)) {
        throw new RuntimeException("Unable to create SQL directory: {$directory}");
    }

    $handle = fopen($path, 'wb');
    if (! $handle) {
        throw new RuntimeException("Unable to write SQL file: {$path}");
    }

    fwrite($handle, "INSERT INTO `indonesia_regions` (`code`, `name`, `postal_code`) VALUES\n");

    $total = count($rows);
    foreach ($rows as $index => $row) {
        $line = sprintf(
            "(%s, %s, %s)%s\n",
            quoteSql($row['code']),
            quoteSql($row['name']),
            quoteNullableString($row['postal_code']),
            $index === $total - 1 ? ';' : ','
        );

        fwrite($handle, $line);
    }

    fclose($handle);
}

function quoteSql(string $value): string
{
    return "'".str_replace(['\\', "'"], ['\\\\', "\\'"], $value)."'";
}

function quoteNullableString(mixed $value): string
{
    if ($value === null || $value === '') {
        return 'NULL';
    }

    return quoteSql((string) $value);
}

function writeManifest(string $path, int $totalRows, string $hash): void
{
    $directory = dirname($path);
    if (! is_dir($directory) && ! mkdir($directory, 0755, true) && ! is_dir($directory)) {
        throw new RuntimeException("Unable to create manifest directory: {$directory}");
    }

    $content = "<?php\n// Auto-generated by CI/CD. DO NOT EDIT.\nreturn [\n"
        ."    'version' => '".gmdate('Y.m.d')."',\n"
        ."    'data_date' => '".gmdate('Y-m-d')."',\n"
        ."    'source_hash' => '{$hash}',\n"
        ."    'generated_at' => '".gmdate('c')."',\n"
        ."    'source' => [\n"
        ."        'repo' => 'aliziodev/laravel-wilayah',\n"
        ."        'branch' => 'main',\n"
        ."        'hash' => '{$hash}',\n"
        ."    ],\n"
        ."    'counts' => [\n"
        ."        'total' => {$totalRows},\n"
        ."    ],\n"
        ."];\n";

    file_put_contents($path, $content);
}
