<?php

declare(strict_types=1);

const DEFAULT_UPSTREAM_REPOSITORY = 'https://github.com/aliziodev/laravel-wilayah.git';
const DEFAULT_UPSTREAM_BRANCH = 'main';
const DEFAULT_DATA_PATH = __DIR__.'/../../data';

$repository = $argv[1] ?? DEFAULT_UPSTREAM_REPOSITORY;
$branch = $argv[2] ?? DEFAULT_UPSTREAM_BRANCH;
$targetDataPath = $argv[3] ?? DEFAULT_DATA_PATH;
$temporaryClonePath = sys_get_temp_dir().DIRECTORY_SEPARATOR.'indonesia-regions-upstream-'.bin2hex(random_bytes(6));

cloneUpstreamRepository($repository, $branch, $temporaryClonePath);

try {
    $rows = copyWilayahData($temporaryClonePath, $targetDataPath);
    $upstreamHash = resolveGitHash($temporaryClonePath);

    writeManifest($targetDataPath.'/version.php', $rows, $upstreamHash, $branch);

    echo "Copied {$rows} rows from {$repository} ({$branch}@{$upstreamHash}) into {$targetDataPath}\n";
} finally {
    deleteDirectory($temporaryClonePath);
}

function loadPhpData(string $path): array
{
    if (! file_exists($path)) {
        throw new RuntimeException("Wilayah data file not found: {$path}");
    }

    $data = require $path;

    return is_array($data) ? $data : [];
}

function copyWilayahData(string $wilayahRoot, string $targetDataPath): int
{
    ensureDirectory($targetDataPath);
    ensureDirectory($targetDataPath.'/districts');
    ensureDirectory($targetDataPath.'/villages');

    $rowCount = 0;

    foreach (['provinces.php', 'regencies.php'] as $file) {
        $source = $wilayahRoot.'/data/'.$file;
        $target = $targetDataPath.'/'.$file;

        copyPhpDataset($source, $target);
        $rowCount += count(loadPhpData($source));
    }

    foreach (['districts', 'villages'] as $directory) {
        $files = glob($wilayahRoot.'/data/'.$directory.'/*.php') ?: [];
        sort($files);

        foreach ($files as $source) {
            $target = $targetDataPath.'/'.$directory.'/'.basename($source);
            copyPhpDataset($source, $target);
            $rowCount += count(loadPhpData($source));
        }
    }

    return $rowCount;
}

function cloneUpstreamRepository(string $repository, string $branch, string $targetPath): void
{
    runCommand([
        'git',
        'clone',
        '--depth=1',
        '--branch',
        $branch,
        $repository,
        $targetPath,
    ]);
}

function resolveGitHash(string $repositoryPath): string
{
    return trim(runCommand(['git', 'rev-parse', 'HEAD'], $repositoryPath));
}

function copyPhpDataset(string $source, string $target): void
{
    if (! file_exists($source)) {
        throw new RuntimeException("Wilayah data file not found: {$source}");
    }

    $content = file_get_contents($source);
    if ($content === false) {
        throw new RuntimeException("Unable to read source dataset: {$source}");
    }

    if (file_put_contents($target, $content) === false) {
        throw new RuntimeException("Unable to write dataset file: {$target}");
    }
}

function ensureDirectory(string $path): void
{
    if (! is_dir($path) && ! mkdir($path, 0755, true) && ! is_dir($path)) {
        throw new RuntimeException("Unable to create directory: {$path}");
    }
}

function writeManifest(string $path, int $totalRows, string $hash, string $branch): void
{
    $directory = dirname($path);
    if (! is_dir($directory) && ! mkdir($directory, 0755, true) && ! is_dir($directory)) {
        throw new RuntimeException("Unable to create manifest directory: {$directory}");
    }

    $content = "<?php\n// Auto-generated by CI/CD. DO NOT EDIT.\nreturn [\n"
        ."    'version' => '".gmdate('Y.m.d')."',\n"
        ."    'data_date' => '".gmdate('Y-m-d')."',\n"
        ."    'source_hash' => '{$hash}',\n"
        ."    'generated_at' => '".gmdate('c')."',\n"
        ."    'source' => [\n"
        ."        'repo' => 'aliziodev/laravel-wilayah',\n"
        ."        'branch' => '{$branch}',\n"
        ."        'hash' => '{$hash}',\n"
        ."    ],\n"
        ."    'counts' => [\n"
        ."        'total' => {$totalRows},\n"
        ."    ],\n"
        ."];\n";

    file_put_contents($path, $content);
}

function runCommand(array $command, ?string $workingDirectory = null): string
{
    $escapedCommand = implode(' ', array_map(static fn (string $part): string => escapeshellarg($part), $command));

    $descriptors = [
        1 => ['pipe', 'w'],
        2 => ['pipe', 'w'],
    ];

    $process = proc_open($escapedCommand, $descriptors, $pipes, $workingDirectory);

    if (! is_resource($process)) {
        throw new RuntimeException('Unable to start command: '.$escapedCommand);
    }

    $stdout = stream_get_contents($pipes[1]) ?: '';
    $stderr = stream_get_contents($pipes[2]) ?: '';

    fclose($pipes[1]);
    fclose($pipes[2]);

    $exitCode = proc_close($process);

    if ($exitCode !== 0) {
        throw new RuntimeException(trim($stderr) !== '' ? trim($stderr) : 'Command failed: '.$escapedCommand);
    }

    return trim($stdout);
}

function deleteDirectory(string $path): void
{
    if (! is_dir($path)) {
        return;
    }

    $items = scandir($path);
    if ($items === false) {
        return;
    }

    foreach ($items as $item) {
        if ($item === '.' || $item === '..') {
            continue;
        }

        $itemPath = $path.DIRECTORY_SEPARATOR.$item;

        if (is_dir($itemPath)) {
            deleteDirectory($itemPath);

            continue;
        }

        unlink($itemPath);
    }

    rmdir($path);
}
