<?php
// Auto-generated by CI/CD. DO NOT EDIT.
return [

    'version' => '2026.07.23',
    'data_date' => '2026-07-23',
    'source_hash' => '20580335d8c6f2c2e422fbed4a8363cd6768f102',
    'generated_at' => '2026-07-23T06:18:30+00:00',
    'source' => [
        'repo' => 'aliziodev/laravel-wilayah',
        'branch' => 'main',
        'hash' => '20580335d8c6f2c2e422fbed4a8363cd6768f102',
    ],
    'counts' => [
        'total' => 91162,
    ],
];
