<?php
// Auto-generated by CI/CD. DO NOT EDIT.
return [
    'version' => '2026.03.07',
    'data_date' => '2026-03-07',
    'source_hash' => 'e36e8f85b75ec2c469ee4f504bbde8fb90ea5c27',
    'generated_at' => '2026-03-07T00:57:18+00:00',
    'source' => [
        'repo' => 'aliziodev/laravel-wilayah',
        'branch' => 'main',
        'hash' => 'e36e8f85b75ec2c469ee4f504bbde8fb90ea5c27',
    ],
    'counts' => [
        'total' => 91162,
    ],
];
