<?php
// Auto-generated by CI/CD. DO NOT EDIT.
return [

    'version' => '2026.06.18',
    'data_date' => '2026-06-18',
    'source_hash' => '02e1c0a1d7944116090aeab94535252c6f17e872',
    'generated_at' => '2026-06-18T08:26:44+00:00',
    'source' => [
        'repo' => 'aliziodev/laravel-wilayah',
        'branch' => 'main',
        'hash' => '02e1c0a1d7944116090aeab94535252c6f17e872',
    ],
    'counts' => [
        'total' => 91162,
    ],
];
